[package]
name = "a2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7.0"
regex = "1.7.1"

[features]
log = []

[lib]
name = "lib"
path = "src/lib.rs"
